<x-layout>
    <x-slot:title>Privacy Policy - {{ site_name_bn() }}</x-slot>

    <div class="py-4 md:py-10 min-h-screen">
        <div class="container">

        <!-- Category Header (breadcrumb only, main title is above image) -->
        <div class="mb-4 md:mb-6 text-left">
            <div class="flex items-center gap-1 text-sm font-bold text-slate-500 mb-3 md:mb-4">
                <!-- Home Icon -->
                <a href="/" class="text-slate-500 hover:text-primary transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                        <polyline points="9 22 9 12 15 12 15 22"></polyline>
                    </svg>
                </a>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="text-slate-300"><path d="m9 18 6-6-6-6"/></svg>
                <span class="text-black font-bold">Privacy Policy</span>
            </div>

            <div class="w-full border-b border-slate-300 relative mb-4 md:mb-8">
                <div class="absolute -bottom-[1px] left-0 w-40 h-[2px] bg-primary"></div>
            </div>
        </div>

        <div class="px-0 lg:px-[300px]">

            {{-- Section title (same as page name) + full-width illustrative image above the privacy text --}}
            <div class="w-full mb-4 md:mb-5 text-left">
                <h2 class="text-2xl md:text-3xl font-bold serif text-title mb-3">
                    Privacy Policy
                </h2>
            </div>

            <div class="w-full mb-6 md:mb-8">
                <div class="img-placeholder w-full aspect-[3/1.4] overflow-hidden shadow-md rounded md:rounded-none">
                    <img
                        src="https://images.unsplash.com/photo-1517244865690-110ee96edfde?w=1600"
                        alt="Privacy and data protection"
                        class="w-full h-full object-cover"
                        onload="this.parentElement.classList.remove('img-placeholder')"
                    >
                </div>
            </div>

            <div class="prose prose-slate max-w-none text-gray-700 leading-relaxed space-y-6 text-base md:text-lg font-semibold text-justify">

            <p>
                Daily Ittefaq is firm to protect your personal information when you are using the website or applications from Daily Ittefaq. This privacy policy relates to use of any personal information that it collects from visitors/readers via following, among other, services:
            </p>

            <ul class="list-disc pl-6 space-y-1">
                <li>any Daily Ittefaq website that links to this privacy policy;</li>
                <li>social media or official Daily Ittefaq content on other websites;</li>
                <li>mobile and web applications (Apps)</li>
            </ul>

            <p>
                In all the above services, the "privacy policy" shall apply only when the application, website or contents therein are truly and genuinely generated by Daily Ittefaq. Provided that no application, website or contents therein are generated or presented at any false or fake website, page or group in the name (or with false logo) of Daily Ittefaq, won't get this protection.
            </p>

            <p>
                Daily Ittefaq collects or receives information about its users for many purposes; for instance, to provide services designed to serve the user, to monitor and improve the services offerings, for marketing or targeting advertisements etc. Such information may include your name, address, phone number, email address, age, social network account etc.
            </p>

            <p>
                There may be other privacy policies that apply to certain services provided by Daily Ittefaq. Visitors are requested to read these while registering or subscribing to these services on these sites. Daily Ittefaq respects the privacy of its visitors/readers and makes use of its best effort to ensure that the information collected is used for the limited purpose for which it was received.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Special Precaution</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                In the name of Daily Ittefaq/ দৈনিক ইত্তেফাক, there may be multiple fake websites and facebook pages and unauthorized/ unwanted facebook groups in online. Daily Ittefaq will hold no responsibility for any content generated, published or shared in those fake websites, unauthorized pages or groups in social media.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">How Daily Ittefaq collects the information</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                Daily Ittefaq collects the information on a user upon the user's access to the Daily Ittefaq website – (i) by registering to the site or Apps, (ii) subscribing to the newsletter, (iii) responding to a survey or participating in a competition, (iv) logging-in to a site or page, etc.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Disclosure of Information Collected</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                Daily Ittefaq does not trade or provide personally identifiable information to any other parties except for those that assist Daily Ittefaq in operating its website, conducting the business and serving the users.
            </p>

            <p>
                Daily Ittefaq may release personally identifiable information if it is required to comply with the laws of Bangladesh.
            </p>

            <p>
                Notwithstanding anything contained in this privacy policy, Daily Ittefaq may disclose or share information collected including personal information to service providers, affiliate companies, consultants or advisors or partners that it has engaged to perform business related functions on its behalf. Daily Ittefaq may also share the information in response to legal process, or protect its interest in any forum. The information may be used for investigating or preventing potentially illegal activities, or situations involving potential threats to any person, us, or the services, or violations of our policies, the law or our "Terms of Use" as well as to verify or enforce compliance with the policies governing our services.
            </p>

            <p>
                The information may as well be shared to offer market products or services to the visitors/readers. However, in all these events or any other event when personal information is shared or disclosed, Daily Ittefaq will use its best endeavors to control the sharing or disclosure and will only share to such an extent as it is required to meet the purpose.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Advertisement</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                The advertisements included in the Daily Ittefaq website and Apps, are by third-party companies and ad networks through independent ad tags, which may collect information about users for which Daily Ittefaq will bear no responsibility that may arise as a result of collecting and/or sharing the information with any other party.
            </p>

            <p>
                Daily Ittefaq will not accept any liability that may arise as a result of any content of any advertisement that may appear on the Daily Ittefaq website.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Third Party Advertisements and links</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                At the discretion of Daily Ittefaq, the website or application may display or allow advertisements of third party services or products. These third-party sites may have separate and independent privacy policies. Daily Ittefaq accepts no responsibility or liability for the content of advertising material, including, without limitation, any error, omission or inaccuracy therein.
            </p>

            <p>
                Daily Ittefaq does not hold any responsibility for information leakage due to the visitor/reader accessing a separate link, application or website, whether through a link in the website or contents of Daily Ittefaq.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Use of Cookies</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                Daily Ittefaq does not collect any user data based on cookies, nor does it store any sort of user information that may be personal to the user.
            </p>

            <p>
                If a third party associated with the Daily Ittefaq website collects user cookies upon your visit to the Daily Ittefaq website, Daily Ittefaq does not control the use of these cookies therefore you should check the relevant third-party website.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Demographic and purchase information</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                We may reference other sources of demographic and other information to provide you with more targeted communications and promotions. We use Google Analytics, among others, to track the user behavior on our website. You can opt-out of Google Analytics for Display Advertising and customize Google Display Network ads using the Ads Settings options provided by Google.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Communication by Daily Ittefaq</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                From time to time, Daily Ittefaq may contact its users via e-mail, phone or SMS for invitation for participation in campaigns/competitions organized by Daily Ittefaq, feedback, survey etc., based on the information it has received from the users.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Accessing the website from outside Bangladesh</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                All personal information submitted by users outside Bangladesh will be processed in accordance with these 'Terms of use' and 'Privacy Policy'.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Governing Law</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                The laws that govern "Privacy Policy" of Daily Ittefaq and its relationship with the user are the laws of Bangladesh and any dispute regarding the use, retention, disclosure, leakage or dissemination of the information or data can only be raised before the courts of Bangladesh which shall have exclusive jurisdiction on this matter. The entire "Privacy Policy" shall apply to all who enter the website, receive service or use an application from Daily Ittefaq regardless of their nationality, location, residence or place of business.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Opt-out</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                If, at any time, the users prefer not to receive email containing marketing information from us, then the user can simply follow the unsubscribe options at the bottom of each email.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Data Retention</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                We shall hold your personal information as long as your account exists with Daily Ittefaq. We will delete your information as soon as reasonably possible, based on account activity and in accordance with applicable law(s), whenever you request us to do so. However, we may archive and/or retain some information for legal purposes.
            </p>

            <p>
                Notwithstanding, Daily Ittefaq may retain data for a long time as per its own internal data retention policy. Please note that there may be events when the erasing/deleting of information may take more time than usual, and Daily Ittefaq shall not hold any responsibility in such events.
            </p>

            <p>
                You may access or modify your personal information by signing on to the website. We will not modify the information provided by you. However, you must update your personal information as soon as such changes are required.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Data Deletion</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                Daily Ittefaq strategies support the deletion of client data. However we prefer such requests to be in writing and made in cooperation with Daily Ittefaq Data Protection and Records management committee.
            </p>

            <p>
                We retain your personal information as long as necessary for us to provide services to you or you ask us to not retain your data. If you no longer want us to use your information then you can request that we erase your personal information and close your Daily Ittefaq account as soon as reasonably possible, based on your account activity and in accordance with applicable law(s).
            </p>

            <p>
                We may retain and use your personal information to the extent necessary to comply with our legal obligations. For example, we may keep some of your information for tax, legal reporting and auditing obligations.
            </p>

            <h2 class="text-xl font-bold text-title mt-8 mb-2">Modification of Privacy Policy</h2>
            <div class="w-10 h-[2px] bg-primary mb-4"></div>

            <p>
                Daily Ittefaq reserves the right to amend, modify, alter, or omit any terms in the "Privacy Policy" at any time but the changed policy will be immediately uploaded or updated in the website. By continuing to use our services after any changes are made, you accept those changes and will be bound by them. We encourage you to periodically check back and review this policy so that visitors/readers will always know what information we collect, how we use it, and with whom we share it.
            </p>

        </div>
        </div>
    </div>
    </div>

</x-layout>
